# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

import os
import sys
sys.path.insert(0, os.path.abspath('.'))

project = 'Ndigo'
copyright = '2023, Sulima'
author = 'Sulima'
release = '1.0'
autosectionlabel_prefix_document = True

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = ['sphinx.ext.autosectionlabel','sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.mathjax', 'sphinx.ext.viewcode','sphinx_numfig','breathe', 'sphinx.ext.mathjax','sphinxcontrib.doxylink']

# Path to the Breathe configuration file (generated by Doxygen)
breathe_projects = {'MyProject': 'Doxygen/xml'}
breathe_default_project = 'MyProject'

latex_elements = {
    'figure_align': 'htbp'
}
doxylink = {
    'doxygen': ('Doxygen/xml', 'xml/'),
}

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme_options = {
    # Other theme options...
    "numfig": True,
}
html_theme = 'sphinx_rtd_theme'
epub_theme = 'epub'
html_static_path = ['docs/_static']
html_css_files = ['style.css']

