name: Build HTML and PDF documentation

on:
  push:
    branches: dev
  # release:
  #   types:
  #     - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # checkout specific branch
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create output directory for doxygen
      run: |
        mkdir build
        mkdir build/doxygen

    - name: Run doxygen
      uses: mattnotmitt/doxygen-action@v1.9.8

    - name: Replace some unicode characters
      run: |
        chmod +x replace_xsd_commands.sh
        sudo ./replace_xsd_commands.sh

    - name: Build documentation
      run: |
        make html
        make latex

    - name: Upload HTML to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html
        path: build/html

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
    - run: |
        ls -a
        ls -a ./artifacts

    # - name: Publish HTML
    #   uses: appleboy/scp-action@v0.1.7
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     port: ${{ secrets.PORT }}
    #     key: ${{ secrets.KEY }}
    #     source: ./build/html/*
    #     target: ${{ secrets.TARGETHTML }}
    #     strip_components: 2
    #     rm: true

    # - name: Publish PDF
    #   uses: appleboy/scp-action@v0.1.7
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     port: ${{ secrets.PORT }}
    #     key: ${{ secrets.KEY }}
    #     source: ./build/latex/Ndigo6G_User_Guide.pdf
    #     target: ${{ secrets.TARGETPDF }}
    #     strip_components: 3
    #     rm: true

    # - name: zip and upload documentation as release asset
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   run: |
    #     mkdir documentation
    #     mv ./artifacts/html ./documentation/html
    #     mv ./artifacts/latex/Ndigo6G_User_Guide.pdf ./documentation/Ndigo6G_User_Guide.pdf
    #     zip -r documentation.zip documentation
    #     gh release upload ${{ github.event.release.tag_name }} ./documentation.zip