name: Build HTML and PDF documentation

on:
  push:
    branches:
      dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # checkout specific branch
        ref: dev

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create output directory for doxygen
      run: |
        mkdir build
        mkdir build/doxygen

    - name: Run doxygen
      uses: mattnotmitt/doxygen-action@v1.9.8

    - name: Replace some unicode characters
      run: |
        chmod +x replace_xsd_commands.sh
        sudo ./replace_xsd_commands.sh

    - name: Build documentation
      run: |
        make html
        make latex

    - name: Upload HTML to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html
        path: build/html

    - name: Compile PDF
      uses: xu-cheng/latex-action@v3
      with:
        root_file: ndigo6g-12userguide.tex
        latexmk_use_lualatex: true
        working_directory: build/latex
        pre_compile: "tlmgr update --self && tlmgr update --all"

    - name: Upload log if latexmk fails
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: latex_files
        path: |
          build/latex/*

    - name: Upload LaTeX to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: latex
        path: build/latex


